schema = 3

[mod]
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.24"
    hash = "sha256-taGKFZFQlR5++5b2oZ1dYS3RERKv6yh1gniNWhb4egg="
  [mod."github.com/stellar/go"]
    version = "v0.0.0-20250311234916-385ac5aca1a4"
    hash = "sha256-/cpVrZ53QFKslxKRtc67D2mR8u/A+S8yERVOcqryzq0="
  [mod."github.com/withObsrvr/pluginapi"]
    version = "v0.0.0-20250303141549-e645e333195c"
    hash = "sha256-FkcFo+g2CJ2VF4i/fm/GA/vrldjKmKml3lBgtovLDbI="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.5"
    hash = "sha256-isupBiQUrKPEFzK94k5cgzM3Ab5fMXp352/zcsXV1JU="
